package generator

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateAccessors(t *testing.T) {
	tests := []struct {
		name          string
		files         map[string]string
		config        Config
		output        string
		want          string
		noExtraFiles  []string
		checkCompiles bool
	}{
		{
			name: "annotated common fields",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

type SharedID string
type SharedVersion int64
type PrivateDetail string
type SharedKey string

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	ID      SharedID
	Version SharedVersion
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	ID           SharedID
	Version      SharedVersion
	RetryCount   int32
	DisplayLabel string
}

// +go-sumtype-accessor=ExampleState
type ThirdVariant struct {
	ID           SharedID
	Version      SharedVersion
	RetryCount   int32
	PrivateValue PrivateDetail
}

type IgnoredVariant struct {
	ID      SharedID
	Version SharedVersion
}

// +go-sumtype-accessor=AnotherState
type AlphaVariant struct {
	Key SharedKey
}

// +go-sumtype-accessor=AnotherState
type BetaVariant struct {
	Key   SharedKey
	Extra string
}
`,
			},
			config: Config{
				Output: "accessors.gen.go",
			},
			output: "accessors.gen.go",
			want: `// Code generated by go-sumtype-accessor; DO NOT EDIT.

package sample

type AnotherState interface {
	isAnotherState()
	GetKey() SharedKey
	SetKey(SharedKey)
}

func (*AlphaVariant) isAnotherState() {}

func (v *AlphaVariant) GetKey() SharedKey {
	return v.Key
}

func (v *AlphaVariant) SetKey(value SharedKey) {
	v.Key = value
}

func (*BetaVariant) isAnotherState() {}

func (v *BetaVariant) GetKey() SharedKey {
	return v.Key
}

func (v *BetaVariant) SetKey(value SharedKey) {
	v.Key = value
}

type ExampleState interface {
	isExampleState()
	GetID() SharedID
	SetID(SharedID)
	GetVersion() SharedVersion
	SetVersion(SharedVersion)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetID() SharedID {
	return v.ID
}

func (v *FirstVariant) SetID(value SharedID) {
	v.ID = value
}

func (v *FirstVariant) GetVersion() SharedVersion {
	return v.Version
}

func (v *FirstVariant) SetVersion(value SharedVersion) {
	v.Version = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetID() SharedID {
	return v.ID
}

func (v *SecondVariant) SetID(value SharedID) {
	v.ID = value
}

func (v *SecondVariant) GetVersion() SharedVersion {
	return v.Version
}

func (v *SecondVariant) SetVersion(value SharedVersion) {
	v.Version = value
}

func (*ThirdVariant) isExampleState() {}

func (v *ThirdVariant) GetID() SharedID {
	return v.ID
}

func (v *ThirdVariant) SetID(value SharedID) {
	v.ID = value
}

func (v *ThirdVariant) GetVersion() SharedVersion {
	return v.Version
}

func (v *ThirdVariant) SetVersion(value SharedVersion) {
	v.Version = value
}
`,
			noExtraFiles:  []string{"examplestate_sumtype.go", "anotherstate_sumtype.go"},
			checkCompiles: true,
		},
		{
			name: "without existing interface",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

type SharedID string

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	ID SharedID
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	ID SharedID
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor; DO NOT EDIT.

package sample

type ExampleState interface {
	isExampleState()
	GetID() SharedID
	SetID(SharedID)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetID() SharedID {
	return v.ID
}

func (v *FirstVariant) SetID(value SharedID) {
	v.ID = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetID() SharedID {
	return v.ID
}

func (v *SecondVariant) SetID(value SharedID) {
	v.ID = value
}
`,
		},
		{
			name: "imported common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

import "time"

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	StartedAt time.Time
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	StartedAt time.Time
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor; DO NOT EDIT.

package sample

import "time"

type ExampleState interface {
	isExampleState()
	GetStartedAt() time.Time
	SetStartedAt(time.Time)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetStartedAt() time.Time {
	return v.StartedAt
}

func (v *FirstVariant) SetStartedAt(value time.Time) {
	v.StartedAt = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetStartedAt() time.Time {
	return v.StartedAt
}

func (v *SecondVariant) SetStartedAt(value time.Time) {
	v.StartedAt = value
}
`,
			checkCompiles: true,
		},
		{
			name: "function common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

import "time"

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	Callback func(time.Time) error
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	Callback func(time.Time) error
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor; DO NOT EDIT.

package sample

import "time"

type ExampleState interface {
	isExampleState()
	GetCallback() func(time.Time) error
	SetCallback(func(time.Time) error)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetCallback() func(time.Time) error {
	return v.Callback
}

func (v *FirstVariant) SetCallback(value func(time.Time) error) {
	v.Callback = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetCallback() func(time.Time) error {
	return v.Callback
}

func (v *SecondVariant) SetCallback(value func(time.Time) error) {
	v.Callback = value
}
`,
			checkCompiles: true,
		},
		{
			name: "anonymous struct common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

import "time"

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	Window struct {
		StartedAt time.Time ` + "`json:\"startedAt\"`" + `
	}
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	Window struct {
		StartedAt time.Time ` + "`json:\"startedAt\"`" + `
	}
}
`,
			},
			output: "sumtype_accessors.go",
			want: "// Code generated by go-sumtype-accessor; DO NOT EDIT.\n\n" +
				"package sample\n\n" +
				"import \"time\"\n\n" +
				"type ExampleState interface {\n" +
				"\tisExampleState()\n" +
				"\tGetWindow() struct {\n" +
				"\t\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"\t}\n" +
				"\tSetWindow(struct {\n" +
				"\t\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"\t})\n" +
				"}\n\n" +
				"func (*FirstVariant) isExampleState() {}\n\n" +
				"func (v *FirstVariant) GetWindow() struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"} {\n" +
				"\treturn v.Window\n" +
				"}\n\n" +
				"func (v *FirstVariant) SetWindow(value struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"}) {\n" +
				"\tv.Window = value\n" +
				"}\n\n" +
				"func (*SecondVariant) isExampleState() {}\n\n" +
				"func (v *SecondVariant) GetWindow() struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"} {\n" +
				"\treturn v.Window\n" +
				"}\n\n" +
				"func (v *SecondVariant) SetWindow(value struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"}) {\n" +
				"\tv.Window = value\n" +
				"}\n",
			checkCompiles: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := writePackage(t, tt.files)
			tt.config.Dir = dir
			if tt.output == "" {
				tt.output = "sumtype_accessors.go"
			}

			if err := Generate(tt.config); err != nil {
				t.Fatalf("Generate() error = %v", err)
			}

			got := readFile(t, filepath.Join(dir, tt.output))
			if got != tt.want {
				t.Fatalf("generated output mismatch (-want +got):\n%s", diffLines(tt.want, got))
			}

			for _, name := range tt.noExtraFiles {
				if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
					t.Fatalf("unexpected generated file %q exists: %v", name, err)
				}
			}

			if tt.checkCompiles {
				assertPackageBuilds(t, dir)
			}
		})
	}
}

func TestLoadPackageReturnsAllPackageErrors(t *testing.T) {
	dir := writePackage(t, map[string]string{
		"go.mod": "module example.com/sample\n\ngo 1.24\n",
		"first.go": `package sample

func BrokenOne(
`,
		"second.go": `package sample

func BrokenTwo(
`,
	})

	_, err := loadPackage(dir)
	if err == nil {
		t.Fatal("loadPackage() error = nil, want package errors")
	}
	joined, ok := err.(interface{ Unwrap() []error })
	if !ok || len(joined.Unwrap()) < 2 {
		t.Fatalf("loadPackage() error = %T, want joined package errors: %v", err, err)
	}
	for _, want := range []string{"first.go", "second.go"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("loadPackage() error missing %q: %v", want, err)
		}
	}
}

func TestLoadPackageIncludesImportsAndDependencies(t *testing.T) {
	dir := writePackage(t, map[string]string{
		"go.mod": "module example.com/sample\n\ngo 1.24\n",
		"dep/dep.go": `package dep

type Value string
`,
		"state.go": `package sample

import "example.com/sample/dep"

type State struct {
	Value dep.Value
}
`,
	})

	pkg, err := loadPackage(dir)
	if err != nil {
		t.Fatalf("loadPackage() error = %v", err)
	}
	imported := pkg.Imports["example.com/sample/dep"]
	if imported == nil {
		t.Fatalf("loadPackage() imports missing dependency: %#v", pkg.Imports)
	}
	if imported.Types == nil || imported.Types.Scope().Lookup("Value") == nil {
		t.Fatalf("loadPackage() dependency types missing Value: %#v", imported.Types)
	}
}

func TestGenerateRejectsMisspelledAnnotation(t *testing.T) {
	dir := writePackage(t, map[string]string{
		"go.mod": "module example.com/sample\n\ngo 1.24\n",
		"state.go": `package sample

type SharedID string

// +go-sumtype-accesor=ExampleState
type FirstVariant struct {
	ID SharedID
}
`,
	})

	err := Generate(Config{Dir: dir})
	if err == nil || !strings.Contains(err.Error(), "no sumtype accessor annotations found") {
		t.Fatalf("Generate() error = %v, want misspelled annotation to be ignored", err)
	}
}

func writePackage(t *testing.T, files map[string]string) string {
	t.Helper()

	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func assertPackageBuilds(t *testing.T, dir string) {
	t.Helper()

	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("skipping generated package build because go command is not available")
	}

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOCACHE="+filepath.Join(t.TempDir(), "go-build"))
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated package does not compile: %v\n%s", err, out)
	}
}

func diffLines(want, got string) string {
	wantLines := strings.SplitAfter(want, "\n")
	gotLines := strings.SplitAfter(got, "\n")
	var b strings.Builder
	for i := 0; i < len(wantLines) || i < len(gotLines); i++ {
		switch {
		case i >= len(wantLines):
			b.WriteString("+")
			b.WriteString(gotLines[i])
		case i >= len(gotLines):
			b.WriteString("-")
			b.WriteString(wantLines[i])
		case wantLines[i] != gotLines[i]:
			b.WriteString("-")
			b.WriteString(wantLines[i])
			b.WriteString("+")
			b.WriteString(gotLines[i])
		}
	}
	return b.String()
}
