package generator

import (
	"go/types"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateAccessors(t *testing.T) {
	tests := []struct {
		name          string
		files         map[string]string
		config        Config
		output        string
		want          string
		noExtraFiles  []string
		checkCompiles bool
	}{
		{
			name: "annotated common fields",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

type SharedID string
type SharedVersion int64
type PrivateDetail string
type SharedKey string

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	ID      SharedID
	Version SharedVersion
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	ID           SharedID
	Version      SharedVersion
	RetryCount   int32
	DisplayLabel string
}

// +go-sumtype-accessor=ExampleState
type ThirdVariant struct {
	ID           SharedID
	Version      SharedVersion
	RetryCount   int32
	PrivateValue PrivateDetail
}

type IgnoredVariant struct {
	ID      SharedID
	Version SharedVersion
}

// +go-sumtype-accessor=AnotherState
type AlphaVariant struct {
	Key SharedKey
}

// +go-sumtype-accessor=AnotherState
type BetaVariant struct {
	Key   SharedKey
	Extra string
}
`,
			},
			config: Config{
				Output: "accessors.gen.go",
			},
			output: "accessors.gen.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

type AnotherState interface {
	isAnotherState()
	GetKey() SharedKey
	SetKey(SharedKey)
}

func (*AlphaVariant) isAnotherState() {}

func (v *AlphaVariant) GetKey() SharedKey {
	return v.Key
}

func (v *AlphaVariant) SetKey(value SharedKey) {
	v.Key = value
}

func (*BetaVariant) isAnotherState() {}

func (v *BetaVariant) GetKey() SharedKey {
	return v.Key
}

func (v *BetaVariant) SetKey(value SharedKey) {
	v.Key = value
}

type ExampleState interface {
	isExampleState()
	GetID() SharedID
	SetID(SharedID)
	GetVersion() SharedVersion
	SetVersion(SharedVersion)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetID() SharedID {
	return v.ID
}

func (v *FirstVariant) SetID(value SharedID) {
	v.ID = value
}

func (v *FirstVariant) GetVersion() SharedVersion {
	return v.Version
}

func (v *FirstVariant) SetVersion(value SharedVersion) {
	v.Version = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetID() SharedID {
	return v.ID
}

func (v *SecondVariant) SetID(value SharedID) {
	v.ID = value
}

func (v *SecondVariant) GetVersion() SharedVersion {
	return v.Version
}

func (v *SecondVariant) SetVersion(value SharedVersion) {
	v.Version = value
}

func (*ThirdVariant) isExampleState() {}

func (v *ThirdVariant) GetID() SharedID {
	return v.ID
}

func (v *ThirdVariant) SetID(value SharedID) {
	v.ID = value
}

func (v *ThirdVariant) GetVersion() SharedVersion {
	return v.Version
}

func (v *ThirdVariant) SetVersion(value SharedVersion) {
	v.Version = value
}
`,
			noExtraFiles:  []string{"examplestate_sumtype.go", "anotherstate_sumtype.go"},
			checkCompiles: true,
		},
		{
			name: "without existing interface",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

type SharedID string

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	ID SharedID
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	ID SharedID
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

type ExampleState interface {
	isExampleState()
	GetID() SharedID
	SetID(SharedID)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetID() SharedID {
	return v.ID
}

func (v *FirstVariant) SetID(value SharedID) {
	v.ID = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetID() SharedID {
	return v.ID
}

func (v *SecondVariant) SetID(value SharedID) {
	v.ID = value
}
`,
		},
		{
			name: "imported common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

import "time"

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	StartedAt time.Time
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	StartedAt time.Time
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

import "time"

type ExampleState interface {
	isExampleState()
	GetStartedAt() time.Time
	SetStartedAt(time.Time)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetStartedAt() time.Time {
	return v.StartedAt
}

func (v *FirstVariant) SetStartedAt(value time.Time) {
	v.StartedAt = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetStartedAt() time.Time {
	return v.StartedAt
}

func (v *SecondVariant) SetStartedAt(value time.Time) {
	v.StartedAt = value
}
`,
			checkCompiles: true,
		},
		{
			name: "function common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

import "time"

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	Callback func(time.Time) error
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	Callback func(time.Time) error
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

import "time"

type ExampleState interface {
	isExampleState()
	GetCallback() func(time.Time) error
	SetCallback(func(time.Time) error)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetCallback() func(time.Time) error {
	return v.Callback
}

func (v *FirstVariant) SetCallback(value func(time.Time) error) {
	v.Callback = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetCallback() func(time.Time) error {
	return v.Callback
}

func (v *SecondVariant) SetCallback(value func(time.Time) error) {
	v.Callback = value
}
`,
			checkCompiles: true,
		},
		{
			name: "anonymous struct common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

import "time"

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	Window struct {
		StartedAt time.Time ` + "`json:\"startedAt\"`" + `
	}
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	Window struct {
		StartedAt time.Time ` + "`json:\"startedAt\"`" + `
	}
}
`,
			},
			output: "sumtype_accessors.go",
			want: "// Code generated by go-sumtype-accessor. DO NOT EDIT.\n\n" +
				"package sample\n\n" +
				"import \"time\"\n\n" +
				"type ExampleState interface {\n" +
				"\tisExampleState()\n" +
				"\tGetWindow() struct {\n" +
				"\t\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"\t}\n" +
				"\tSetWindow(struct {\n" +
				"\t\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"\t})\n" +
				"}\n\n" +
				"func (*FirstVariant) isExampleState() {}\n\n" +
				"func (v *FirstVariant) GetWindow() struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"} {\n" +
				"\treturn v.Window\n" +
				"}\n\n" +
				"func (v *FirstVariant) SetWindow(value struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"}) {\n" +
				"\tv.Window = value\n" +
				"}\n\n" +
				"func (*SecondVariant) isExampleState() {}\n\n" +
				"func (v *SecondVariant) GetWindow() struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"} {\n" +
				"\treturn v.Window\n" +
				"}\n\n" +
				"func (v *SecondVariant) SetWindow(value struct {\n" +
				"\tStartedAt time.Time `json:\"startedAt\"`\n" +
				"}) {\n" +
				"\tv.Window = value\n" +
				"}\n",
			checkCompiles: true,
		},
		{
			name: "multi-name and embedded common fields",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

type Embedded struct {
	Value string
}

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	Embedded
	Primary, Secondary string
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	Embedded
	Primary, Secondary string
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

type ExampleState interface {
	isExampleState()
	GetEmbedded() Embedded
	SetEmbedded(Embedded)
	GetPrimary() string
	SetPrimary(string)
	GetSecondary() string
	SetSecondary(string)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetEmbedded() Embedded {
	return v.Embedded
}

func (v *FirstVariant) SetEmbedded(value Embedded) {
	v.Embedded = value
}

func (v *FirstVariant) GetPrimary() string {
	return v.Primary
}

func (v *FirstVariant) SetPrimary(value string) {
	v.Primary = value
}

func (v *FirstVariant) GetSecondary() string {
	return v.Secondary
}

func (v *FirstVariant) SetSecondary(value string) {
	v.Secondary = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetEmbedded() Embedded {
	return v.Embedded
}

func (v *SecondVariant) SetEmbedded(value Embedded) {
	v.Embedded = value
}

func (v *SecondVariant) GetPrimary() string {
	return v.Primary
}

func (v *SecondVariant) SetPrimary(value string) {
	v.Primary = value
}

func (v *SecondVariant) GetSecondary() string {
	return v.Secondary
}

func (v *SecondVariant) SetSecondary(value string) {
	v.Secondary = value
}
`,
			checkCompiles: true,
		},
		{
			name: "generic annotated structs",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

// +go-sumtype-accessor=ExampleState
type FirstVariant[T any] struct {
	Value T
}

// +go-sumtype-accessor=ExampleState
type SecondVariant[T any] struct {
	Value T
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

type ExampleState[T any] interface {
	isExampleState()
	GetValue() T
	SetValue(T)
}

func (*FirstVariant[T]) isExampleState() {}

func (v *FirstVariant[T]) GetValue() T {
	return v.Value
}

func (v *FirstVariant[T]) SetValue(value T) {
	v.Value = value
}

func (*SecondVariant[T]) isExampleState() {}

func (v *SecondVariant[T]) GetValue() T {
	return v.Value
}

func (v *SecondVariant[T]) SetValue(value T) {
	v.Value = value
}
`,
			checkCompiles: true,
		},
		{
			name: "generic composite common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

// +go-sumtype-accessor=ExampleState
type FirstVariant[T any] struct {
	Items  []T
	Lookup map[string]T
}

// +go-sumtype-accessor=ExampleState
type SecondVariant[T any] struct {
	Items  []T
	Lookup map[string]T
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

type ExampleState[T any] interface {
	isExampleState()
	GetItems() []T
	SetItems([]T)
	GetLookup() map[string]T
	SetLookup(map[string]T)
}

func (*FirstVariant[T]) isExampleState() {}

func (v *FirstVariant[T]) GetItems() []T {
	return v.Items
}

func (v *FirstVariant[T]) SetItems(value []T) {
	v.Items = value
}

func (v *FirstVariant[T]) GetLookup() map[string]T {
	return v.Lookup
}

func (v *FirstVariant[T]) SetLookup(value map[string]T) {
	v.Lookup = value
}

func (*SecondVariant[T]) isExampleState() {}

func (v *SecondVariant[T]) GetItems() []T {
	return v.Items
}

func (v *SecondVariant[T]) SetItems(value []T) {
	v.Items = value
}

func (v *SecondVariant[T]) GetLookup() map[string]T {
	return v.Lookup
}

func (v *SecondVariant[T]) SetLookup(value map[string]T) {
	v.Lookup = value
}
`,
			checkCompiles: true,
		},
		{
			name: "generic union constraint",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

// +go-sumtype-accessor=ExampleState
type FirstVariant[T ~int | ~string] struct {
	Value T
}

// +go-sumtype-accessor=ExampleState
type SecondVariant[T ~int | ~string] struct {
	Value T
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

type ExampleState[T interface {
	~int | ~string
}] interface {
	isExampleState()
	GetValue() T
	SetValue(T)
}

func (*FirstVariant[T]) isExampleState() {}

func (v *FirstVariant[T]) GetValue() T {
	return v.Value
}

func (v *FirstVariant[T]) SetValue(value T) {
	v.Value = value
}

func (*SecondVariant[T]) isExampleState() {}

func (v *SecondVariant[T]) GetValue() T {
	return v.Value
}

func (v *SecondVariant[T]) SetValue(value T) {
	v.Value = value
}
`,
			checkCompiles: true,
		},
		{
			name: "block comment annotation",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

type SharedID string

/*
+go-sumtype-accessor=ExampleState
*/
type FirstVariant struct {
	ID SharedID
}

/*
 +go-sumtype-accessor=ExampleState
*/
type SecondVariant struct {
	ID SharedID
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

type ExampleState interface {
	isExampleState()
	GetID() SharedID
	SetID(SharedID)
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetID() SharedID {
	return v.ID
}

func (v *FirstVariant) SetID(value SharedID) {
	v.ID = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetID() SharedID {
	return v.ID
}

func (v *SecondVariant) SetID(value SharedID) {
	v.ID = value
}
`,
			checkCompiles: true,
		},
		{
			name: "anonymous interface common field types",
			files: map[string]string{
				"go.mod": "module example.com/sample\n\ngo 1.24\n",
				"state.go": `package sample

import "time"

// +go-sumtype-accessor=ExampleState
type FirstVariant struct {
	Handler interface {
		Handle(time.Time) error
	}
}

// +go-sumtype-accessor=ExampleState
type SecondVariant struct {
	Handler interface {
		Handle(time.Time) error
	}
}
`,
			},
			output: "sumtype_accessors.go",
			want: `// Code generated by go-sumtype-accessor. DO NOT EDIT.

package sample

import "time"

type ExampleState interface {
	isExampleState()
	GetHandler() interface {
		Handle(time.Time) error
	}
	SetHandler(interface {
		Handle(time.Time) error
	})
}

func (*FirstVariant) isExampleState() {}

func (v *FirstVariant) GetHandler() interface {
	Handle(time.Time) error
} {
	return v.Handler
}

func (v *FirstVariant) SetHandler(value interface {
	Handle(time.Time) error
}) {
	v.Handler = value
}

func (*SecondVariant) isExampleState() {}

func (v *SecondVariant) GetHandler() interface {
	Handle(time.Time) error
} {
	return v.Handler
}

func (v *SecondVariant) SetHandler(value interface {
	Handle(time.Time) error
}) {
	v.Handler = value
}
`,
			checkCompiles: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := writePackage(t, tt.files)
			tt.config.Dir = dir
			if tt.output == "" {
				tt.output = "sumtype_accessors.go"
			}

			if err := Generate(tt.config); err != nil {
				t.Fatalf("Generate() = %v", err)
			}

			got := readFile(t, filepath.Join(dir, tt.output))
			if got != tt.want {
				t.Fatalf("generated output mismatch (-want +got):\n%s", diffLines(tt.want, got))
			}

			for _, name := range tt.noExtraFiles {
				if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
					t.Fatalf("unexpected generated file %q exists: %v", name, err)
				}
			}

			if tt.checkCompiles {
				assertPackageBuilds(t, dir)
			}
		})
	}
}

func TestSameFieldTypeRejectsDistinctNamedTypesWithSamePackageName(t *testing.T) {
	leftPkg := types.NewPackage("example.com/left/dup", "dup")
	rightPkg := types.NewPackage("example.com/right/dup", "dup")
	left := types.NewNamed(types.NewTypeName(0, leftPkg, "Value", nil), types.Typ[types.String], nil)
	right := types.NewNamed(types.NewTypeName(0, rightPkg, "Value", nil), types.Typ[types.String], nil)

	if sameFieldType(left, right) {
		t.Fatal("sameFieldType() = true, want false for distinct named types with matching printed names")
	}
}

func TestSameFieldTypeComparesUnions(t *testing.T) {
	anyConstraint := types.NewInterfaceType(nil, nil).Complete()
	leftParam := types.NewTypeParam(types.NewTypeName(0, nil, "T", nil), anyConstraint)
	sameParam := types.NewTypeParam(types.NewTypeName(0, nil, "T", nil), anyConstraint)
	left := types.NewUnion([]*types.Term{
		types.NewTerm(true, types.Typ[types.Int]),
		types.NewTerm(false, types.NewSlice(leftParam)),
	})
	same := types.NewUnion([]*types.Term{
		types.NewTerm(true, types.Typ[types.Int]),
		types.NewTerm(false, types.NewSlice(sameParam)),
	})
	different := types.NewUnion([]*types.Term{
		types.NewTerm(true, types.Typ[types.Int]),
		types.NewTerm(false, types.Typ[types.String]),
	})

	if !sameFieldType(left, same) {
		t.Fatal("sameFieldType() = false, want true for matching unions with matching type parameter names")
	}
	if sameFieldType(left, different) {
		t.Fatal("sameFieldType() = true, want false for different union terms")
	}
}

func TestTypeRendererPanicsOnUnsupportedType(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("typeRenderer.code() did not panic for unsupported type")
		}
	}()

	typeRenderer{}.code(unsupportedType{})
}

type unsupportedType struct{}

func (unsupportedType) Underlying() types.Type {
	return unsupportedType{}
}

func (unsupportedType) String() string {
	return "unsupported"
}

func TestLoadPackageReturnsAllPackageErrors(t *testing.T) {
	dir := writePackage(t, map[string]string{
		"go.mod": "module example.com/sample\n\ngo 1.24\n",
		"first.go": `package sample

func BrokenOne(
`,
		"second.go": `package sample

func BrokenTwo(
`,
	})

	_, err := loadPackage(dir)
	if err == nil {
		t.Fatal("loadPackage() = nil, want package errors")
	}
	joined, ok := err.(interface{ Unwrap() []error })
	if !ok || len(joined.Unwrap()) < 2 {
		t.Fatalf("loadPackage() = %T, want joined package errors: %v", err, err)
	}
	for _, want := range []string{"first.go", "second.go"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("loadPackage() missing %q: %v", want, err)
		}
	}
}

func TestLoadPackageReturnsDependencyPackageErrors(t *testing.T) {
	dir := writePackage(t, map[string]string{
		"go.mod": "module example.com/sample\n\ngo 1.24\n",
		"dep/dep.go": `package dep

func BrokenDep(
`,
		"state.go": `package sample

import "example.com/sample/dep"

type State struct {
	Value dep.Value
}
`,
	})

	_, err := loadPackage(dir)
	if err == nil {
		t.Fatal("loadPackage() = nil, want dependency package errors")
	}
	if !strings.Contains(err.Error(), filepath.Join("dep", "dep.go")) {
		t.Fatalf("loadPackage() missing dependency file: %v", err)
	}
}

func TestLoadPackageIncludesImportsAndDependencies(t *testing.T) {
	dir := writePackage(t, map[string]string{
		"go.mod": "module example.com/sample\n\ngo 1.24\n",
		"dep/dep.go": `package dep

type Value string
`,
		"state.go": `package sample

import "example.com/sample/dep"

type State struct {
	Value dep.Value
}
`,
	})

	pkg, err := loadPackage(dir)
	if err != nil {
		t.Fatalf("loadPackage() = %v", err)
	}
	imported := pkg.Imports["example.com/sample/dep"]
	if imported == nil {
		t.Fatalf("loadPackage() imports missing dependency: %#v", pkg.Imports)
	}
	if imported.Types == nil || imported.Types.Scope().Lookup("Value") == nil {
		t.Fatalf("loadPackage() dependency types missing Value: %#v", imported.Types)
	}
}

func TestGenerateRejectsMisspelledAnnotation(t *testing.T) {
	dir := writePackage(t, map[string]string{
		"go.mod": "module example.com/sample\n\ngo 1.24\n",
		"state.go": `package sample

type SharedID string

// +go-sumtype-accesor=ExampleState
type FirstVariant struct {
	ID SharedID
}
`,
	})

	err := Generate(Config{Dir: dir})
	if err == nil || !strings.Contains(err.Error(), "no sumtype accessor annotations found") {
		t.Fatalf("Generate() = %v, want misspelled annotation to be ignored", err)
	}
}

func writePackage(t *testing.T, files map[string]string) string {
	t.Helper()

	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func assertPackageBuilds(t *testing.T, dir string) {
	t.Helper()

	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("skipping generated package build because go command is not available")
	}

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOCACHE="+filepath.Join(t.TempDir(), "go-build"))
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated package does not compile: %v\n%s", err, out)
	}
}

func diffLines(want, got string) string {
	wantLines := strings.SplitAfter(want, "\n")
	gotLines := strings.SplitAfter(got, "\n")
	var b strings.Builder
	for i := 0; i < len(wantLines) || i < len(gotLines); i++ {
		switch {
		case i >= len(wantLines):
			b.WriteString("+")
			b.WriteString(gotLines[i])
		case i >= len(gotLines):
			b.WriteString("-")
			b.WriteString(wantLines[i])
		case wantLines[i] != gotLines[i]:
			b.WriteString("-")
			b.WriteString(wantLines[i])
			b.WriteString("+")
			b.WriteString(gotLines[i])
		}
	}
	return b.String()
}
